name: Release

on:
  workflow_run:
    workflows: ['Build Default', 'Build MKL Mac/Linux']
    types: [completed]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Print out packages
        run: ls -la dist/*

      - name: Upload wheels to pypi
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          python -m pip install --upgrade twine
          twine upload dist/*
